# Generated by Django 4.1.7 on 2023-03-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_remove_coursedetail_instructor_and_more'),
        ('students', '0003_alter_studentprofile_enrolled_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, to='courses.course'),
        ),
    ]
