# Generated by Django 4.1.7 on 2023-03-24 09:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_delete_coursedetail_course_instructors_and_more'),
        ('students', '0004_alter_studentprofile_enrolled_courses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentProfile',
            new_name='Student',
        ),
    ]
