# Generated by Django 4.1.7 on 2023-03-24 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_remove_coursedetail_instructor_and_more'),
        ('students', '0004_alter_studentprofile_enrolled_courses'),
        ('instructors', '0003_instructor_delete_instructordetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseDetail',
        ),
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(blank=True, to='instructors.instructor'),
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.course'),
        ),
    ]
