# Generated by Django 4.1.7 on 2023-03-24 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rename_coursecatgory_coursecategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='course_module',
            new_name='module',
        ),
    ]
