# Generated by Django 4.1.7 on 2023-03-24 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('BAM', 'Business Administration and Management'), ('HPR', 'Health Professions and Related Programs'), ('SSH', 'Social Sciences and History'), ('P', 'Psychology'), ('BBS', 'Biological and Biomedical Sciences'), ('E', 'Engineering'), ('PSST', 'Physical Sciences and Science Technologies')], max_length=100)),
                ('vacancy', models.CharField(max_length=50)),
                ('short_bio', models.TextField(blank=True, max_length=300, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.coursedetail')),
            ],
        ),
    ]
