# Generated by Django 4.1.7 on 2023-03-24 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instructors', '0003_instructor_delete_instructordetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='vacancy',
            new_name='designation',
        ),
        migrations.AlterField(
            model_name='instructor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
